/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qian_NativeCaller */

#ifndef _Included_com_qian_NativeCaller
#define _Included_com_qian_NativeCaller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qian_NativeCaller
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_qian_NativeCaller_getStringFromNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
